---
title: "Fish Data from raw"
author: "Giulio"
date: "16/08/2019"
output: html_document
---

```{r}
library(tidyverse)

if(!"quantreg" %in% installed.packages()){
  install.packages("quantreg")
}


if(!"here" %in% installed.packages()){
  install.packages("here")
}

library(here)
setwd(here())

library(curl)
```

download the Rdata

```{r}
curl_download("https://ndownloader.figshare.com/files/12927221", here("../Data/Fish/Fish.Rdata"))
```

load in memory

```{r}
Fish_data <- load(here("../Data/Fish/Fish.Rdata"))
```

it loads a `MatPa_Final_ok` dataframe.

```{r}
library(tidyverse)
```
```{r}
MatPa_Final_ok %>% glimpse()
```

```{r}
file <- here("../Data/Fish/Data.Rdata")
"https://ndownloader.figshare.com/files/3079757" %>%
  curl_download(file)

Data <-load(here("../Data/Fish/Data.Rdata"))
```

get da code

```{r}
curl_download("https://ndownloader.figshare.com/files/3079760", here("R/Gravel_Nature_2019.R"))
```
we source it so we create the final matrix of who eats whom (code will complain while creating an artificial dataset because a `Ball` thingy is not created, but we don't care about it.)

```{r}
source(here("R/Gravel_Nature_2019.R"))
```
the final matrix is named `Cor_mat` and the log of fish body size is named `BS_med`.

```{r}
Cor_mat %>%
  as_tibble() %>%
  write_csv(here("../Outputs/Data/Fish/adj.csv"))

BS_med %>%
  enframe(name = "names", value = "Body_size_log") %>%
  write_csv(here("../Outputs/Data/Fish/metadata.csv"))
```


