---
title: "Data_munging"
author: "Giulio"
date: "12/08/2019"
output: html_document
---
```{r}
library(tidyverse)

if(!"here" %in% installed.packages()){
  install.packages("here")
}

library(here)
setwd(here())

if(!"tidygraph" %in% installed.packages()){
  devtools::install_github('thomasp85/tidygraph')
}

library(tidygraph)
```

read the edge list

```{r}
edge_list_karate <-
  read_tsv(here("../Data/Karate/karate.txt"),
           col_names = c("from","to"),
           col_types = cols(
             from = col_character(),
             to = col_character()
           )
  ) %>%
  as_tibble()
```


and turn it into an adj matrix. The graph is simmetric and simple. We'll use `tidygraph` for that.

```{r}
adj_karate <- edge_list_karate %>%
  tbl_graph(edges = .) %>%
  to_undirected() %>%
  activate("nodes") %>%
  arrange(as.integer(name)) %>%
  igraph::as_adj() %>%
  as.matrix()
```

The metadata in `karate_faction.txt`.

```{r}
meta_karate <- read_csv(
  here("../Data/Karate/karate_faction.txt"),
  col_names = "Faction"
  ) %>%
  rowid_to_column("names")
```
save it in something meaningful

```{r}
meta_karate %>%
  write_csv(path = here("../Outputs/Data/Karate/metadata.csv"))
```

and write the matrices

```{r}
temp_path <- paste0(here("../Outputs/Data/Karate/adj.csv"))
  
adj_karate %>%
    as_tibble(.name_repair = "check_unique") %>%
    write_csv(temp_path)
```


